# Generated by Django 5.0.6 on 2024-06-01 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(choices=[('Dr', 'Doctor'), ('Sp', 'specialist')], default='Dr', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_traninig', models.CharField(blank=True, max_length=50, null=True)),
                ('image_of_training', models.ImageField(blank=True, null=True, upload_to='trainings/')),
                ('voice', models.FileField(blank=True, null=True, upload_to='audio_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('diagnosis', models.TextField()),
                ('recommendations', models.TextField()),
                ('comments', models.TextField(blank=True, default='No connents yet', null=True)),
                ('name_of_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='Home.doctor')),
                ('treatment_plan', models.ForeignKey(blank=True, default='طماطم', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='Home.training')),
            ],
        ),
    ]
